on:
  push:
    branches:
      - master
    paths:
      - "src/processing/**"

env:
  IMAGE_VERSION: "1"
  IMAGE_TAG: "${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: prenaissance
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/processing/Dockerfile
          push: true
          tags: |
            prenaissance/processing:${{ env.IMAGE_VERSION }}
            prenaissance/processing:${{ env.IMAGE_TAG }}
            prenaissance/processing:latest
