name: Processing CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore src/processing
      - name: Build
        run: dotnet build src/processing --no-restore
      - name: Test
        run: dotnet test src/processing.tests
