on:
  push:
    branches:
      - master
    paths:
      - "src/processing/**"
      - ".github/workflows/processing-docker.yml"

env:
  IMAGE_VERSION: "1"
  IMAGE_TAG: "${{ github.sha }}"
  IMAGE_NAME: prenaissance/pricing-tf-processing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: prenaissance
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/processing/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
