on:
  push:
    branches:
      - master
    paths:
      - "src/webapi/**"
      - "src/common/**"
      - ".github/workflows/webapi-docker.yml"

env:
  IMAGE_VERSION: "1"
  IMAGE_TAG: "${{ github.sha }}"
  IMAGE_NAME: prenaissance/pricing-tf-webapi
  TARGET_PLAFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: prenaissance
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/webapi/Dockerfile
          push: true
          platforms: ${{ env.TARGET_PLAFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
